### ISSUE TITLE
Unable to click on list of possible start node

### ISSUE THREAD

**Issue by AlasdairGray** [HW-SWeL/Validata#24]
Clicking on the select start node option result in the following. 
![screen shot 2015-03-09 at 20 54 43](https://cloud.githubusercontent.com/assets/1141265/6564191/90fa5a10-c69e-11e4-9c0a-10ac1785ade2.png)

It looks like the dropdown is confined to be within its container.

**Comment by AlasdairGray** [comment]
May have something to do with the data not validating first as now that the data is validating the drop down list works.

**Comment by beveradb** [comment]
Is this still an issue with the current version deployed on http://shextool.eu?

**Comment by AlasdairGray** [comment]
I believe this has been fixed in the latest version
