### ISSUE TITLE
Deployment instructions

### ISSUE THREAD

**Issue by AlasdairGray** [HW-SWeL/Validata#31]
The readme states that you just need to copy the files in the public directory. However, when deployed several files in a components directory are then missing.

Please update the deployment instructions.

**Comment by beveradb** [comment]
Will do this evening. However to get you started, you just need to run "bower install" from the project directory to fetch these resources.

**Comment by beveradb** [comment]
(that is of course assuming you have nodejs and bower installed; if not, first install node according to https://nodejs.org/ then install bower with npm install -g bower )

**Comment by AlasdairGray** [comment]
Thanks for the tips. I hadn't come across bower before.

Sent by Outlookhttp://taps.io/outlookmobile for Android

On Tue, Jun 23, 2015 at 8:24 AM -0700, "Andrew Beveridge" <notifications@github.com<mailto:notifications@github.com>> wrote:

(that is of course assuming you have nodejs and bower installed; if not, first install node according to https://nodejs.org/ then install bower with npm install -g bower )

—
Reply to this email directly or view it on GitHubhttps://github.com/HeriotWattMEng2015/Validata/issues/31#issuecomment-114544150.

---

We invite research leaders and ambitious early career researchers to 
join us in leading and driving research in key inter-disciplinary themes. 
Please see www.hw.ac.uk/researchleaders for further information and how
to apply.

Heriot-Watt University is a Scottish charity
registered under charity number SC000278.

**Comment by AlasdairGray** [comment]
I;ve made a correction to these and some other bits of the code, but I don't have write access to the repository. Can you allow me to edit the repository?

**Comment by beveradb** [comment]
Updated readme with clear instructions, added Alasdair to group (which I believe gives you write access?)
