### ISSUE TITLE
Implement Admin Panel for creating config file

### ISSUE THREAD

**Issue by skhutan** [HW-SWeL/Validata#6]
This will be a standalone front-end tool for a Validata administrator to generate a configuration file for the Validata UI. This configuration file will then be uploaded via FTP (or whatever) to the Validata directory to be ready by it. For now, this just needs to be a simple static web interface to allow a user to upload ShEx schemas and give them a title and description. Once they've uploaded and described all the schemas they want to be available to Validata users, a click of a button should generate a JSON file with the configuration and trigger download. Ideally this tool should also support uploading / importing an existing configuration file, modifying the settings in it and downloading the modified version to avoid needing to duplicate the uploading of every schema to add a new one. Exactly what format the JSON file is in is not important, as long as it is intuitive. It must be able to store a number of schemas with (at least) names and descriptions, but likely other properties in the future. It should also be able to store other Validata settings / options in the future. As the output from this is required by the ShEx Validata UI, it is part of the same repository and codebase, with primary html file located here: https://github.com/HeriotWattMEng2015/ShExValidata/blob/master/public/admin.html

**Comment by beveradb** [comment]
Implemented; see http://shextool.eu/admin
